import { Link } from 'react-router-dom';
import { ArrowUpRight, ShieldCheck } from 'lucide-react';
import { PageHeading, Badge, Note, Loading, ErrorNotice } from '../../components/common/UI.jsx';
import { useResource } from '../../hooks/useResource.js';
import { getMeta } from '../../services/api/client.js';
import './Methodology.css';
const ruleNames = {dependency:'Declared dependency',configuration:'Project configuration',language:'GitHub language data',source:'Source signal',readme:'README mention',multipleRepositories:'Direct evidence in multiple repositories',commitActivity:'Candidate-attributed repository commits',recentActivity:'Repository contribution within 90 days',testing:'Repository test-path indicators',deployment:'Repository deployment configuration'};
export default function Methodology() {
  const {data,loading,error,reload} = useResource('scoring-meta',getMeta);
  return <><PageHeading eyebrow="Transparent by design" title="No black box. Just evidence." description="Here’s how SkillProof turns a limited snapshot of public work into an explainable report."/><div className="methodology-intro mb-7"><ShieldCheck size={26} className="shrink-0 text-[#668b49]"/><p className="text-sm leading-7">A resume is a claim. A repository offers signals. SkillProof connects them using a documented rule set and shows its reasoning. <strong className="font-semibold">A person’s ability is larger than their public GitHub footprint.</strong></p></div>
    <div className="grid items-start gap-6 xl:grid-cols-2"><section className="panel p-6 sm:p-8"><h2 className="mb-6 text-xl font-bold">Three evidence states</h2><div className="space-y-6">{[['Proven',data ? `At least ${data.scoring.thresholds.proven} points with a direct signal. Meaningful supporting evidence was found.` : 'Direct evidence meets the configured score threshold.'],['Partial',data ? `At least ${data.scoring.thresholds.partial} points, below the proven threshold. Evidence is limited.` : 'Evidence exists, but does not meet the proven threshold.'],['Claimed-only','A resume claim without sufficiently strong evidence in the repositories inspected.']].map(([status,text]) => <div key={status}><Badge status={status}/><p className="muted mt-2">{text}</p></div>)}</div></section><section className="panel p-6 sm:p-8"><h2 className="mb-5 text-xl font-bold">What adds to the score?</h2>{loading ? <Loading text="Loading configured scoring rules…"/> : error ? <ErrorNotice error={error} retry={reload}/> : <><div className="space-y-3">{Object.entries(data.scoring.weights).map(([rule,points]) => <div className="flex justify-between gap-4 border-b border-line pb-3 text-xs last:border-0" key={rule}><span className="text-muted">{ruleNames[rule] || rule}</span><strong className="font-semibold">+{points}</strong></div>)}</div><p className="mt-4 text-[11px] leading-5 text-muted">Dependency, configuration, language, and source signals use only the strongest base value. Each supporting rule counts once. The total is capped at 100. Repository context bonuses require direct skill evidence in that repository. Version {data.scoring.version}.</p></>}</section></div>
    <section className="panel my-6 p-6 sm:p-8"><h2 className="text-xl font-bold">Skill Coverage, explained.</h2><p className="muted mt-3">Only the job’s required skills form the denominator. Verified skills count as one, partial skills count as one half, and claimed-only or missing skills count as zero.</p><div className="my-6 overflow-x-auto rounded-xl bg-[#f1f5e9] px-5 py-5 font-mono text-xs leading-6 text-forest">Skill Coverage = (Verified + Partial × 0.5) / Required skills × 100</div><p className="muted">Preferred skills are shown separately. When no required skills are detected, coverage is unavailable. A task marked “Completed by me” never changes a score; publish the work and start a new candidate analysis.</p></section>
    <section className="panel mb-6 p-6 sm:p-8"><h2 className="text-xl font-bold">The boundaries matter.</h2><ul className="mt-5 grid list-disc gap-x-10 gap-y-4 pl-5 text-sm leading-6 text-muted md:grid-cols-2"><li>Only public, non-fork, non-archived, non-empty repositories are eligible.</li><li>Repository selection and file inspection are capped. Some evidence will be missed.</li><li>Dependency declarations and documentation can be stale or unused.</li><li>Commit metrics are a candidate-authored sample, not lifetime or skill-specific totals.</li><li>Test files are indicators. SkillProof does not run project tests.</li><li>Deployment configuration and README URLs do not establish a live deployment.</li><li>PDF extraction is heuristic and has no OCR. Names and section boundaries may be imperfect.</li><li>Job extraction uses a skill dictionary. Ambiguous language can affect the required/preferred distinction.</li></ul></section><Note>These classifications describe evidence availability. They do not independently verify identity, authorship, competence, or hiring suitability.</Note><Link to="/analyze" className="btn btn-primary mt-7">Start an evidence report<ArrowUpRight size={16}/></Link>
  </>;
}
