import { Link } from 'react-router-dom';
import { ArrowUpRight, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Badge } from '../common/UI.jsx';
import './SkillTable.css';
export default function SkillTable({skills,analysisId,compact=false}) {
  const [query,setQuery] = useState(''); const [status,setStatus] = useState('All');
  const filtered = useMemo(() => skills.filter(skill => `${skill.name} ${skill.category}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All' || skill.status === status)),[skills,query,status]);
  return <div className="panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-line px-5 py-5 sm:px-6"><div><h2 className="text-base font-bold">{compact ? 'Skill verification overview' : 'Skill evidence'}</h2><p className="mt-1 text-xs text-muted">Select a skill to see what supports it.</p></div>{compact ? <Link to={`/analysis/${analysisId}/skills`} className="flex items-center gap-1 text-xs font-semibold">All skills<ArrowUpRight size={14}/></Link> : <span className="rounded-lg bg-paper px-3 py-1.5 text-xs text-muted">{skills.length} skills</span>}</div>
    {!compact && <div className="flex flex-wrap gap-3 border-b border-line p-5"><div className="relative min-w-44 flex-1"><Search size={16} className="absolute left-3 top-3.5 text-muted"/><input className="input pl-9" aria-label="Search skills" placeholder="Search skills or categories…" value={query} onChange={e => setQuery(e.target.value)}/></div><select className="input w-auto" aria-label="Filter by status" value={status} onChange={e => setStatus(e.target.value)}>{['All','Proven','Partial','Claimed-only'].map(s => <option key={s}>{s}</option>)}</select></div>}
    <div className="overflow-x-auto"><table className="skill-table"><thead><tr><th>Skill</th><th>Status</th><th>Evidence score</th><th>Sources</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{(compact ? filtered.slice(0,6) : filtered).map(skill => <tr key={skill.id}><td><Link className="font-semibold hover:underline" to={`/analysis/${analysisId}/skills/${skill.id}`}>{skill.name}</Link><span className="mt-1 block text-[10px] text-muted">{skill.claimed ? skill.category : `${skill.category} · GitHub-discovered`}</span></td><td><Badge status={skill.status}/></td><td><div className="flex items-center gap-3"><span className="w-7 text-xs font-semibold tabular-nums">{skill.score}</span><span className="score-track"><span className={`score-fill ${skill.status === 'Partial' ? 'score-partial' : ''}`} style={{width:`${skill.score}%`}}/></span></div></td><td className="text-xs text-muted">{skill.evidence.length} {skill.evidence.length === 1 ? 'signal' : 'signals'}</td><td><Link className="inline-flex rounded-lg p-2 text-muted hover:bg-paper hover:text-ink" aria-label={`View ${skill.name} evidence`} to={`/analysis/${analysisId}/skills/${skill.id}`}><ArrowUpRight size={16}/></Link></td></tr>)}</tbody></table></div>
    {!filtered.length && <p className="px-6 py-12 text-center text-sm text-muted">{skills.length ? 'No skills match these filters.' : 'No dictionary skills or direct GitHub signals were found.'}</p>}
  </div>;
}
