import { useState } from 'react';
import { Check, LoaderCircle, Circle, RotateCcw } from 'lucide-react';
import { analysisApi } from '../../services/api/analysisApi.js';
import { ErrorNotice, Note } from '../common/UI.jsx';
import './AnalysisProgress.css';
const stages = [['resume','Processing resume'],['github','Fetching GitHub profile'],['repositories','Analyzing repositories'],['evidence','Collecting evidence'],['scoring','Scoring skills'],['report','Generating report']];
export default function AnalysisProgress({analysis,reload}) {
  const [error,setError] = useState(''); const [busy,setBusy] = useState(false);
  const index = Math.max(1,stages.findIndex(([key]) => key === analysis.stage));
  const retry = async () => {setBusy(true); try {await analysisApi.retry(analysis._id); reload();} catch(e){setError(e.message);} finally {setBusy(false);}};
  if (analysis.status === 'failed') return <div className="panel mx-auto max-w-2xl p-8"><h2 className="mb-4 text-2xl font-bold">We couldn’t finish this report.</h2><ErrorNotice error={analysis.error?.message || 'Analysis was interrupted.'}/><p className="muted my-5">Your resume is saved. Retry after the issue is resolved to continue the analysis.</p>{error && <ErrorNotice error={error}/>}<button className="btn btn-primary mt-4" disabled={busy} onClick={retry}><RotateCcw size={16}/>{busy ? 'Queuing…' : 'Retry analysis'}</button></div>;
  return <div className="panel mx-auto max-w-2xl p-7 sm:p-10"><div className="mb-7 flex items-center gap-4"><div className="rounded-2xl bg-[#eff5e7] p-4 text-[#628747]"><LoaderCircle className="animate-spin" size={27}/></div><div><h2 className="text-xl font-bold">Following the evidence.</h2><p className="muted mt-1">@{analysis.githubUsername} · {analysis.status === 'queued' ? 'Waiting for an available worker' : 'Analysis in progress'}</p></div></div><div className="mb-7" role="progressbar" aria-label="Analysis progress" aria-valuenow={analysis.progress} aria-valuemin={0} aria-valuemax={100}><div className="mb-2 flex justify-between text-xs text-muted"><span>Report progress</span><span>{analysis.progress}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-paper"><div className="h-full rounded-full bg-[#90ba67] transition-[width]" style={{width:`${analysis.progress}%`}}/></div></div><ol className="space-y-4">{stages.map(([key,label],i) => <li className={`flex items-center gap-3 text-sm ${i === index ? 'font-semibold text-ink' : 'text-muted'}`} key={key}>{i < index ? <Check size={17} className="text-[#65894c]"/> : i === index ? <LoaderCircle size={17} className="animate-spin"/> : <Circle size={17} className="text-[#c4ccbd]"/>}{label}{i === 0 && <span className="ml-auto text-xs text-muted">Complete</span>}</li>)}</ol><div className="mt-8"><Note>Progress reflects completed backend stages. You can leave and reopen this report from Saved reports. Hosting wake-up and GitHub rate limits can affect the time required.</Note></div></div>;
}
