import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight, Target } from 'lucide-react';
import { useResource } from '../../hooks/useResource.js';
import { useReports } from '../../context/ReportContext.jsx';
import { jobApi } from '../../services/api/jobApi.js';
import { Badge, ErrorNotice, Loading, PageHeading, Note } from '../../components/common/UI.jsx';
import { ExportKey, ImportKey } from '../../components/common/AccessKey.jsx';
import TaskCard from '../../components/jobs/TaskCard.jsx';
import { skillLabel } from '../../utils/format.js';
import './JobDetail.css';
export default function JobDetail() {
  const {id} = useParams(); const {reports} = useReports(); const token = reports.find(r => r.type === 'job' && r.id === id)?.token;
  const {data:job,loading,error,reload,setData} = useResource(`job:${id}:${token}`,signal => jobApi.get(id,signal));
  if(loading) return <Loading/>;
  if(error) return <><ErrorNotice error={error} retry={reload}/>{error.code === 'ACCESS_DENIED' && <ImportKey id={id} type="job"/>}</>;
  return <><Link className="mb-6 inline-flex items-center gap-2 text-xs font-semibold text-muted" to="/jobs"><ArrowLeft size={14}/>Analyze another role</Link><PageHeading eyebrow="Job match report" title={job.title || 'Role requirements'} description={job.analysisId ? 'Your public evidence, mapped to the role’s required skills.' : 'Required and preferred technical skills extracted from this description.'} action={<ExportKey id={id} type="job"/>}/>
    {job.analysisId ? <><div className="mb-7 grid gap-5 lg:grid-cols-[1.2fr_1fr]"><section className="coverage-panel"><div className="flex items-center justify-between"><p className="text-xs font-medium text-[#c9d7c2]">Skill Coverage</p><Target size={20} className="text-lime"/></div><p className="my-5 font-display text-6xl font-bold tracking-tight text-white">{job.coverage === null ? '—' : `${job.coverage}%`}</p><p className="max-w-md text-xs leading-5 text-[#c9d7c2]">{job.coverage === null ? 'No required dictionary skills were found. There is no denominator to calculate coverage.' : 'Verified skills count fully. Partial skills count halfway. Only required skills are included.'}</p><Link to={`/analysis/${job.analysisId}`} className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-lime">View candidate evidence<ArrowUpRight size={14}/></Link></section><div className="grid gap-3">{[{label:'Verified matches',count:job.summary.verified,status:'Verified'},{label:'Partial matches',count:job.summary.partial,status:'Partial'},{label:'Skill gaps',count:job.summary.gaps,status:'Gap'}].map(item => <div key={item.label} className="panel flex items-center justify-between px-6 py-4"><div><p className="mb-1 text-xs text-muted">{item.label}</p><Badge status={item.status}/></div><strong className="font-display text-3xl font-bold">{item.count}</strong></div>)}</div></div>
      <section className="panel mb-7 overflow-hidden"><div className="px-6 py-5"><h2 className="font-bold">The requirement-by-requirement view</h2><p className="mt-1 text-xs text-muted">{job.summary.required} required skills identified</p></div><div className="divide-y divide-line">{job.matches.map(match => <article className="flex flex-wrap items-start justify-between gap-4 p-6" key={match.skill}><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-3"><h3 className="text-sm font-bold">{match.name}</h3><Badge status={match.state}/></div><p className="text-xs leading-5 text-muted">{match.reason}</p><p className="mt-2 text-[10px] text-muted">Candidate status: {match.candidateStatus} · Evidence score: {match.score}/100 · {match.evidence.length} signals</p></div>{match.candidateStatus !== 'Missing' && <Link className="inline-flex items-center gap-1 text-xs font-semibold" to={`/analysis/${job.analysisId}/skills/${match.skill}`}>Evidence<ArrowUpRight size={14}/></Link>}</article>)}{!job.matches.length && <p className="muted border-t border-line p-6">No required skills could be matched. Review the extracted requirements below.</p>}</div></section>
    </> : <div className="mb-7"><Note>No candidate report was selected, so no coverage score or candidate gaps were generated. <Link to="/jobs" className="underline">Select a report to create a match.</Link></Note></div>}
    <div className="mb-7 grid gap-5 md:grid-cols-2">{[['Required skills',job.requiredSkills],['Preferred skills',job.preferredSkills]].map(([label,skills]) => <section className="panel p-6" key={label}><h2 className="mb-4 text-sm font-bold">{label}</h2><div className="flex flex-wrap gap-2">{skills.length ? skills.map(skill => <span key={skill} className="rounded-lg border border-line bg-paper px-3 py-1.5 text-xs">{skillLabel(skill)}</span>) : <p className="text-xs text-muted">None identified by the dictionary.</p>}</div>{label === 'Preferred skills' && <p className="mt-4 text-[11px] text-muted">Shown for context; excluded from Skill Coverage.</p>}</section>)}</div>
    {job.microTasks.length > 0 && <section className="mb-7"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow mb-2">Make your next project count</p><h2 className="text-2xl font-bold tracking-tight">Build evidence for the gaps.</h2><p className="muted mt-2">Focused tasks for missing and partial skills, with a clear definition of done.</p></div><span className="text-xs text-muted">{job.microTasks.filter(t => t.status === 'done').length} / {job.microTasks.length} completed by you</span></div><div className="grid gap-5 md:grid-cols-2 2xl:grid-cols-3">{job.microTasks.map(task => <TaskCard key={task.skill} task={task} jobId={id} onUpdate={setData}/>)}</div></section>}
    {job.analysisId && job.microTasks.length === 0 && job.requiredSkills.length > 0 && <div className="panel mb-7 bg-[#f0f6e9] p-6"><h2 className="font-bold">All identified required skills have verified matches.</h2><p className="muted mt-2">Review the evidence and the role’s wider requirements to understand the complete picture.</p></div>}
    <details className="panel mb-6 p-6"><summary className="cursor-pointer text-sm font-semibold">Original job description</summary><p className="mt-5 whitespace-pre-wrap break-words text-sm leading-7 text-muted">{job.jobDescription}</p></details><Note>{job.warnings.map((warning,i) => <p key={i}>{warning}</p>)}<p>Coverage is an evidence metric, not a hiring prediction.</p></Note>
  </>;
}
