import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Fingerprint } from 'lucide-react';
import { useAnalysis } from '../../hooks/useAnalysis.js';
import ReportGate from '../../components/dashboard/ReportGate.jsx';
import EvidenceList from '../../components/evidence/EvidenceList.jsx';
import RepositoryCard from '../../components/dashboard/RepositoryCard.jsx';
import { Badge, PageHeading, EmptyState, Note, ExternalLink } from '../../components/common/UI.jsx';
import { formatDate } from '../../utils/format.js';
import './SkillDetail.css';
export default function SkillDetail() {
  const {skill:skillId} = useParams(); const resource = useAnalysis();
  return <ReportGate resource={resource}>{analysis => {
    const skill = analysis.skills.find(s => s.id === skillId);
    if (!skill) return <EmptyState title="Skill not found" description="This skill is not part of the candidate’s report." action={<Link to={`/analysis/${analysis._id}/skills`} className="btn btn-primary">View all skills</Link>}/>;
    const repositories = analysis.repositories.filter(repo => skill.repositories.includes(repo.name));
    return <><Link className="mb-6 inline-flex items-center gap-2 text-xs font-semibold text-muted" to={`/analysis/${analysis._id}/skills`}><ArrowLeft size={14}/>Back to skills</Link><PageHeading eyebrow={`${skill.category} / ${skill.claimed ? 'Resume claim' : 'Discovered on GitHub'}`} title={skill.name} description={`Public evidence collected for @${analysis.githubUsername}.`} action={<Badge status={skill.status}/>}/><div className="grid items-start gap-6 xl:grid-cols-[1.7fr_1fr]"><div><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">Follow the evidence</h2><span className="text-xs text-muted">{skill.evidence.length} signals</span></div><EvidenceList evidence={skill.evidence}/></div><aside className="space-y-5"><div className="panel p-6"><div className="mb-5 flex items-center justify-between"><p className="eyebrow">Evidence score</p><Fingerprint size={18} className="text-muted"/></div><p className="font-display text-5xl font-bold tracking-tight">{skill.score}<span className="ml-2 text-base font-normal text-muted">/ 100</span></p><p className="muted mt-4">{skill.reasons[0]}</p><div className="my-5 border-t border-line"/><h3 className="mb-4 text-xs font-semibold">How the score adds up</h3><div className="space-y-3">{skill.breakdown.length ? skill.breakdown.map(item => <div key={item.rule} className="flex justify-between gap-4 text-xs"><span className="leading-5 text-muted">{item.rule}</span><span className="font-semibold text-[#5c803f]">+{item.points}</span></div>) : <p className="text-xs text-muted">No scoring signals found.</p>}</div><p className="mt-5 text-[10px] text-muted">Capped at 100 · Scoring version {analysis.scoringVersion}</p><Link to="/methodology" className="mt-4 inline-block text-xs font-semibold underline underline-offset-4">Read the scoring rules</Link></div><Note>Dependencies and configuration show project signals. Commits, tests, and deployment files provide repository context; they do not prove skill-specific contributions or successful execution.</Note></aside></div>
      <section className="panel mt-7 overflow-hidden"><div className="px-6 py-5"><h2 className="font-bold">Linked repositories</h2><p className="mt-1 text-xs text-muted">Inspect the original work and recent candidate-attributed commits.</p></div>{repositories.map(repo => <div key={repo.fullName}><RepositoryCard repository={repo}/>{repo.commits.length > 0 && <details className="px-6 pb-5 text-xs text-muted"><summary className="cursor-pointer font-medium">Recent sampled commits in {repo.name}</summary><ul className="mt-3 space-y-3">{repo.commits.map(commit => <li key={commit.sha} className="flex flex-wrap justify-between gap-2"><ExternalLink href={commit.url} className="text-[#5c803f]">{commit.sha.slice(0,7)} · {commit.message}</ExternalLink><span>{formatDate(commit.date)}</span></li>)}</ul></details>}</div>)}{!repositories.length && <p className="muted border-t border-line p-6">No inspected repositories provided evidence for this skill.</p>}</section>
    </>;
  }}</ReportGate>;
}
