import { Router } from 'express';
import mongoose from 'mongoose';
import { rateLimit } from 'express-rate-limit';
import * as analysis from '../controllers/analysis.controller.js';
import * as jobs from '../controllers/jobs.controller.js';
import { uploadResume } from '../middlewares/upload.js';
import { validateId } from '../middlewares/validation.js';
import { SKILLS } from '../data/skills.js';
import { SCORING } from '../config/scoring.js';
import { env } from '../config/env.js';
import { searchOntology } from '../ontology/ontology.service.js';
export const router = Router();
const limited = { success: false, error: { code: 'RATE_LIMITED', message: 'Too many requests. Please try again later.' } };
const analysisLimit = rateLimit({ windowMs: 60 * 60 * 1000, limit: 10, standardHeaders: 'draft-8', legacyHeaders: false, message: limited });
const jobLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: 30, standardHeaders: 'draft-8', legacyHeaders: false, message: limited });
const searchLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: 120, standardHeaders: 'draft-8', legacyHeaders: false, message: limited });
router.get('/health', (req,res) => { const ready = mongoose.connection.readyState === 1; res.status(ready ? 200 : 503).json({ success: ready, ...(ready ? { data: { status: 'ok', service: 'skillproof-api' } } : { error: { code: 'DATABASE_UNAVAILABLE', message: 'Database connection is unavailable.' } }) }); });
router.get('/meta', (req,res) => res.json({ success: true, data: { maxFileSizeMb: env.MAX_FILE_SIZE_MB, maxRepositories: env.MAX_REPOSITORIES, skills: SKILLS.map(({id,name,category}) => ({id,name,category})), scoring: SCORING } }));
router.get('/ontology/search', searchLimit, (req, res) => res.json({ success: true, data: searchOntology(req.query.q) }));
router.post('/analysis', analysisLimit, uploadResume, analysis.create);
router.use('/analysis/:id', validateId);
router.get('/analysis/:id', analysis.read);
router.get('/analysis/:id/skills', analysis.skills);
router.get('/analysis/:id/skills/:skill', analysis.skill);
router.get('/analysis/:id/repositories', analysis.repositories);
router.post('/analysis/:id/retry', analysisLimit, analysis.retry);
router.post('/analysis/:id/reanalyze', analysisLimit, analysis.reanalyze);
router.get('/analysis/:id/diff', analysis.diff);
router.delete('/analysis/:id', analysis.remove);

router.post('/jobs/analyze', jobLimit, jobs.create);
router.use('/jobs/:id', validateId);
router.get('/jobs/:id', jobs.read);
router.get('/jobs/:id/match', jobs.match);
router.patch('/jobs/:id/tasks/:skill', jobs.task);
