import { useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowUpRight, Plus, Upload, FileText, BriefcaseBusiness, KeyRound, Search, Trash2 } from 'lucide-react';
import { useReports } from '../../context/ReportContext.jsx';
import { PageHeading, EmptyState, ErrorNotice, Badge, Note } from '../../components/common/UI.jsx';
import { formatDate } from '../../utils/format.js';
import './Reports.css';
export default function Reports() {
  const {reports,remember,forget} = useReports(); const [query,setQuery] = useState(''); const [type,setType] = useState('all'); const [error,setError] = useState('');
  const input = useRef(null); const navigate = useNavigate();
  const visible = reports.filter(r => (type === 'all' || r.type === type) && (r.label || '').toLowerCase().includes(query.toLowerCase()));
  async function importFile(event) {
    const file = event.target.files[0]; if (!file) return;
    try { if(file.size > 10000) throw new Error(); const report = JSON.parse(await file.text()); if (!['analysis','job'].includes(report.type) || !/^[a-f\d]{24}$/i.test(report.id) || !/^[a-f\d]{64}$/.test(report.token)) throw new Error(); remember({type:report.type,id:report.id,token:report.token,label:String(report.label || 'Imported report').slice(0,120),createdAt:report.createdAt || new Date().toISOString()}); navigate(report.type === 'analysis' ? `/analysis/${report.id}` : `/jobs/${report.id}`); }
    catch {setError('Choose a valid SkillProof access-key JSON file, smaller than 10 KB.');} finally {event.target.value='';}
  }
  const removeLocal = report => { if(window.confirm('Remove this key from this browser? The server report will remain. Save the access key first if you need it later.')) forget(report.type,report.id); };
  return <><PageHeading eyebrow="Your workspace" title="Pick up where you left off." description="Reports created or imported in this browser. Keep an access-key backup to open them elsewhere." action={<div className="flex gap-2"><input ref={input} type="file" accept="application/json,.json" className="hidden" onChange={importFile}/><button className="btn btn-secondary" onClick={() => input.current.click()}><Upload size={15}/>Import key</button><Link className="btn btn-primary" to="/analyze"><Plus size={16}/>New analysis</Link></div>}/>{error && <div className="mb-5"><ErrorNotice error={error}/></div>}
    {!reports.length ? <EmptyState title="Your evidence workspace starts here." description="Create a candidate report to connect resume claims with public GitHub work. Your reports will appear here." action={<Link to="/analyze" className="btn btn-primary">Analyze your first candidate<ArrowUpRight size={16}/></Link>}/> : <><div className="mb-5 flex flex-wrap gap-3"><div className="relative min-w-48 flex-1"><Search size={16} className="absolute left-4 top-3.5 text-muted"/><input className="input pl-10" aria-label="Search saved reports" placeholder="Search reports…" value={query} onChange={e => setQuery(e.target.value)}/></div><select className="input w-auto" aria-label="Filter report type" value={type} onChange={e => setType(e.target.value)}><option value="all">All reports</option><option value="analysis">Candidate analyses</option><option value="job">Job analyses</option></select></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visible.map(report => <article key={`${report.type}:${report.id}`} className="panel p-6"><div className="mb-5 flex items-start justify-between"><span className="rounded-xl bg-[#eef3e6] p-3 text-[#678549]">{report.type === 'analysis' ? <FileText size={21}/> : <BriefcaseBusiness size={21}/>}</span><Badge status={report.status || 'Saved'}/></div><p className="eyebrow mb-2">{report.type === 'analysis' ? 'Candidate analysis' : 'Job analysis'}</p><h2 className="truncate text-base font-bold">{report.label}</h2><p className="mt-2 text-[11px] text-muted">Created {formatDate(report.createdAt)}</p><div className="mt-6 flex items-center justify-between border-t border-line pt-4"><Link className="inline-flex items-center gap-2 text-xs font-semibold" to={report.type === 'analysis' ? `/analysis/${report.id}` : `/jobs/${report.id}`}>Open report<ArrowUpRight size={15}/></Link><button className="rounded-md p-1.5 text-muted hover:bg-red-50 hover:text-red-700" aria-label={`Forget local key for ${report.label}`} onClick={() => removeLocal(report)}><Trash2 size={14}/></button></div></article>)}</div>{!visible.length && <EmptyState title="No matching reports" description="Try a different search or report type."/>}</>}
    <div className="mt-6"><Note><span className="inline-flex items-center gap-1.5 font-medium"><KeyRound size={13}/>Your keys stay in this browser.</span><p className="mt-1">Clearing browser storage removes access unless you saved the key file. Removing a local key does not delete server data; use “Delete report and resume” inside the candidate overview for that.</p></Note></div>
  </>;
}
